version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      # <Puerto expuesto> : < Puerto dentro del container>
      # Solo para desarrollo. Comentar en produccion
      - '5432:5432'
    expose:
      # Abre el puerto 5432 en el container al exterior sin tocar nada de la configuración del postgresql
      # Solo para desarrollo. Comentar en produccion
      - '5432'
  odoo:
    image: odoo:16.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold module_technical_name /mnt/extra-addons
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - odoo_log:/var/log/odoo/
      - odoo_data:/var/lib/odoo
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
  mailserver:
    image: greenmail/standalone:1.6.11
    ports:
      - 8081:8080 # API-REST para consultar y gestionar servidor
      # expose:
      # # Por defecto, este contenedor expone los siguientes
      # # puertos (3000 + número de puerto por defecto)
      # - 3025 # SMTP Correo saliente
      # - 3110 # POP3 Correo entrante (descarga de mensajes)
      # - 3143 # IMAP Correo entrante (alternativa a POP3)
      # - 3465 # SMTPS SMTP sobre TLS/SSL
      # - 3993 # IMAPS IMAP sobre TLS/SSL
      # - 3995 # POP3S POP3 sobre TLS/SSL
  webmail:
    image: roundcube/roundcubemail:1.6.0-apache
    depends_on:
      - mailserver
    ports:
      - 8082:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver # servidor IMAP
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143 # puerto IMAP
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver # servidor SMTP
      - ROUNDCUBEMAIL_SMTP_PORT=3025 # servidor SMTP
volumes:
    pgdata:
    odoo_log:
    odoo_data:
